services:
  - type: web
    name: discord-table-bot-python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        value: votre_token_ici